export const SET_LOGIN_PENDING = 'SET_LOGIN_PENDING';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const SET_EDITPROFILE_PENDING = 'SET_EDITPROFILE_PENDING';
export const SET_EDITPROFILE_SUCESS = 'SET_EDITPROFILE_SUCESS';
export const SET_EDITPROFILE_ERROR = 'SET_EDITPROFILE_ERROR';
